up to date

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,7 @@ jobs:
             echo "Starting deployment to VPS..."
 
             # Navigate to the project directory
-            cd /var/www/html/saifalikhan/saif-ali-khan-server || exit
+            cd /var/www/html/saifalikhan/api || exit
 
             # Ensure Git is available
             if ! command -v git &> /dev/null; then
@@ -40,8 +40,8 @@ jobs:
 
             echo "Setting up environment variables..."
             if [ ! -f .env ]; then
-              echo ".env file not found. Copying from .env.example..."
-              cp .env.example .env
+              echo ".env file not found. Copying from .example.env..."
+              cp .example.env .env
             fi
 
             echo "Installing dependencies..."
@@ -53,7 +53,7 @@ jobs:
             # Restart application using PM2
             if command -v pm2 &> /dev/null; then
               echo "Restarting application using PM2..."
-              pm2 restart  saif-server || pm2 start npm --name "saif-server" -- run start
+              pm2 restart  api-saifalikhan || pm2 start npm --name "api-saifalikhan" -- run start
             else
               echo "PM2 not found. Please install it using 'npm install -g pm2'."
               exit 1
